module.exports = {
    api : {
        auth: {
            login:              "/auth/login",
            signup:             "/auth/signup",
            user: {
                get:            "/auth/user",
                edit:           "/auth/user/edit",
            },
            email: {
                code:           "/auth/email/code",
                duplicate:      "/auth/email/duplicate",
                identification: "/auth/email/identification",
                change_pwd:     "/auth/email/change_pwd",
            },
            company: {
                get:            "/auth/company",
                edit:           "/auth/company/edit",
            },
            sns:{
                naver_callback: "/auth/naver/callback",
                signup:         "/auth/signup/sns",
                naver:          "/auth/naver",
                kakao:          "/auth/kakao",
                google:         "/auth/google",
            },
            nickname_duplicate: "/auth/nickname/duplicate",
            validate_token:     "/auth/validate_token",
            reset_password:     "/auth/reset_password",
        },        
        author: {
            get:                "/author",
            update:             "/author",
            create:             "/author",
        },
        bank: {
            get:                "/bank",
        },
        book: {
            get:                "/book/",
            list:               "/book",
            put:                "/book",
            modify:             "/book/modify",
            download:           "/book/download",
            downloadFree:       "/book/download/free",
            preview:            "/book/preview",
            getDetailList:      "/book/detail/",
            main:               "/book/main",
            delete:             "/book/",
            recommend:          "/book/recommend",
        },
        book_detail: {
            get:                "/book_detail/",
            delete:             "/book_detail/",
            modify:             "/book_detail/",
        },
        cart: {
            create:             "/cart",
            duplicate:          "/cart/duplicate",
            list:               "/cart",
            delete:             "/cart/",
            clear:              "/cart/clear",
        },
        category: {
            list:               "/category",
        },
        favorite: {
            author: {
                create:         "/favorite_author",
                get:            "/favorite_author/",
                list:           "/favorite_author",
                delete:         "/favorite_author/",
                duplicate:      "/favorite_author/duplicate",
            },
            book: {
                create:         "/favorite_book",
                get:            "/favorite_book/",
                list:           "/favorite_book",
                delete:         "/favorite_book/",
                duplicate:      "/favorite_book/duplicate",
            },
        },
        member: {
            get:                "/member",
            getById:            "/member/",
            nickname_duplicate: "/member/nickname/duplicate",
            password:           "/member/password",
            passwordCheck:      "/member/password/check",
            upload_profile:     "/member/upload_profile",
            profile:            "/member/profile/",
            certifications:     "/member/certifications",
            update:             "/member/",
            delete:             "/member",
        },
        notification: {
            getNotification:    "/notification/",
            getAllNotiCount:    "/notification/allCount",
            getAllNewNoticount:    "/notification/allNewNotiCount",
            putReadNotification:    "/notification/",
            getNewNotiCount: "/notification/newNotiCnt",
            deleteNotification: "/notification/delete",
        },
        payment: {
            create              :"/payment",
        },
        purchase: {
            list:               "/purchase",
            duplicate:          "/purchase/duplicate",
            sales:              "/purchase/sales",
            sales_ratio:        "/purchase/sales/ratio",
            sales_author:       "/purchase/sales/author",
            sales_book:         "/purchase/sales/book",
            sales_amount_author:"/purchase/sales/amount/author",
        },
        register: {
            book_single:        "/book/single",
            book_series:        "/book/series",
            bookDetail:         "/book_detail"
        },
        review: {
            getReivewList:      "/review",
            getByMember:        "/review/member/",
            getByAuthor:        "/review/author/",
            getByBook:          "/review/book/",
            register:           "/review",
            duplicate:          "/review/duplicate",
            stats:              "/review/stats",
        },
        withdrawal: {
            create:             "/withdrawal",
            get:                "/withdrawal",
        },
        terms: {
            getTerms: "/terms/",
        }
    },
    service : {
        accounts: {
            login               : "/login",
            signup              : "/signup",
            signup_step         : "/signup/step",
            welcome             : "/welcome",
            find_email          : "/login/findpwd",
            change_pwd          : "/change_pwd",
            change_pwd_complete : "/change_pwd/complete",
        },
        auth: {
            naver               : "/auth/callback/naver",
            kakao               : "/auth/callback/kakao",
            google              : "/auth/callback/google",
        },
        author                  : "/author/",
        book: {
            book                : "/book/",
            modify              : "/modify/pub/",
            modify_series       : "/modify/series/",
        },
        buy: {
            buy                 : "/buy",
            callback            : "/buy/callback",
            complete            : "/complete",
        },
        home                    : "/",
        mypage: {
            info                : "/mypage",
            password_change     : "/mypage/password/update",
            notification_change : "/mypage/notification/update",
            leave               : "/leave",
            purchases           : "/purchases",
            carts               : "/carts",
            fav_author          : "/favorite/author",
            fav_book            : "/favorite/book",
            register            : "/register/author/",
        },
        notification    : "/notification/",
        terms           : "/terms/",
        search          : "/search",
        payment         : "/payment",
        register: {
            author              : "/register/author",
            author_detail       : "/register/author/detail",
            book                : "/register/book/",
        },
        review          : "/review/",
    }
};
